[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relative-path = "1.9.3"
rocket = { version = "0.5.1" ,  features = ["json"] }
rocket_cors = "0.6.0"
