name: Node Fix and Lint
'on':
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install npm dependecies
        run: npm ci
      - name: ESLint lint
        run: npm run lint
      - name: ESLint fix
        run: npm run lint:fix
      - name: Commit & push if clean
        if: success()
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-fix JavaScript code via ESLint"
          git push
