name: Node Linter

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      
      - name: Install dependencies
        working-directory: server/nodeJs_server
        run: npm install

      # Run ESLint
      - name: ESLint
        working-directory: server/nodeJs_server/
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: ESLint fix
        if: success()
        working-directory: server/nodeJs_server/
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix

      - name: Commit & Push
        if: success()
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-fix JavaScript code via ESLint"
          git push
