name: Node Lint

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo to docker
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

    
      - name: ESLint fix
        run: npx eslint --fix . --ext .js,.jsx,.ts,.tsx

      - name: Commit & push if clean
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-fix JavaScript/TypeScript code via ESLint"
          git push
