name: Python linter and syntax fixer
'on':
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8
      - name: Create Flake8 config
        run: |
          echo "[flake8]" > .flake8
          echo "exclude = env, __pycache__, ExempleArr.py" >> .flake8
          echo "max-line-length = 100" >> .flake8
      - name: Run Flake8
        run: flake8 . --count --show-source --statistics
      - name: fix formatting with autopep8
        run: autopep8 --in-place --aggressive --aggressive --recursive .
      - name: Commit & push changes
        if: success()
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-fix Python code using autopep8"
          git push
